# Generated by Django 5.1 on 2025-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Issue_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
